version: '2'
services:
  #mysql
  mysql:
    image: mysql:5.7
    restart: always
    container_name: mysql
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d/
      - ./mysql/sql:/opt/sql
      - /mydata/mysql/log:/var/log/mysql
      - /mydata/mysql/data:/var/lib/mysql
      - /mydata/mysql/conf:/etc/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    networks: #加入指定网络
      - group_purchase
  #redis
  redis:
    image: redis
    restart: always
    container_name: redis
    volumes:
      - /mydata/redis/data:/data #数据文件挂载
    command: redis-server --requirepass 123456
    ports:
      - "6379:6379"
    networks: #加入指定网络
      - group_purchase
  #activemq
  activemq:
    image: rmohr/activemq
    restart: always
    container_name: activemq
    volumes:
      - /mydata/activemq/data:/opt/activemq/data
    ports:
      - "61616:61616"
      - "8161:8161"
    networks: #加入指定网络
      - group_purchase
  #mongo
  mongo:
    image: mongo
    restart: always
    container_name: mongo
    volumes:
      - /mydata/mongo/db:/data/db #数据文件挂载
    ports:
      - "27017:27017"
    networks: #加入指定网络
      - group_purchase
  #xxl-job
  xxl-job:
    image: xuxueli/xxl-job-admin:2.1.2
    restart: always
    container_name: xxl-job
    ports:
      - "8080:8080"
    # link 到mysql 需要使用内部端口
    environment:
      PARAMS: '--spring.datasource.url=jdbc:mysql://mysql:3306/xxl_job?Unicode=true&characterEncoding=UTF-8 --spring
       .datasource.username=root  --spring.datasource.password=123456'
    networks: #加入指定网络
      - group_purchase
    depends_on:
      - mysql
  #group-purchase
  group-purchase:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: group-purchase
    ports:
      - "8088:8088"
    environment:
      PARAMS: '--wechat.open.componentAppId=aaa
        --wechat.open.componentSecret=bbb
        --wechat.open.componentToken=ccc
        --wechat.open.componentAesKey=ddd'
    networks: #加入指定网络
      - group_purchase
    depends_on:
      - mongo
      - activemq
      - redis
      - mysql
      - xxl-job
networks:
  group_purchase:
    driver: bridge